name: parcel-pipeline
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: golang:1.23.0
    steps:
    - uses: actions/checkout@v4

    - name: Run Unit Tests
      run: GOOS=linux GOARCH=amd64 go test

    - name: Vet
    run: |
      go vet./...

  deploy:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    needs: test
    steps:
     - name: Checkout
       uses: actions/checkout@v4

     - name: Set up Docker buildx
       uses:  docker/setup-buildx-action@v3

     - name: Log in to DockerHub
       uses: docker/login-action@v3
       with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.ACCESS_TOKEN }}

     - name: Build and push Docker Image
       uses: docker/build-push-action@v5
       with:
       context: .
       push: true



